### ISSUE TITLE
Internal error: recordPublishedPhotoUrl: must be called after recordPublishedPhotoId

### ISSUE THREAD

**Issue by limaco** [flingo64/PhotoStation-Upload-Lr-Plugin#15]
Error with popup window on every photo published.

Internal error: recordPublishedPhotoUrl: must be called after recordPublishedPhotoId

Windows 10

 The log says nothing:

{"success":true,"err_msg":"","duplicate_folder":false}
17:17:25, TRACE: uploadPictureFile: C:\Users\carlos\AppData\Local\Temp\32499A8F-174C-47C6-8EE5-093A98412366\f15479264_XL.jpg dstDir 2012 - Berlin dstFn f15479264.jpg type THUM_XL pos MIDDLE size 336491 --> timeout 30
17:17:25, DEBUG: uploadPictureFile: LrHttp.post(https://mynas.com/photo/include/asst_file_upload.php, timeout: 30, fileSize: 336491
17:17:25, DEBUG: postHeaders:
17:17:25, DEBUG: Field: Content-Type Value: image/jpeg
17:17:25, DEBUG: Field: X-PATH Value: 2012%20%2D%20Berlin
17:17:25, DEBUG: Field: X-DUPLICATE Value: OVERWRITE
17:17:25, DEBUG: Field: X-ORIG-FNAME Value: f15479264%2Ejpg
17:17:25, DEBUG: Field: X-UPLOAD-TYPE Value: THUM_XL
17:17:25, DEBUG: Got Body:
{"success":true,"err_msg":"","duplicate_folder":false}
17:17:25, TRACE: uploadPictureFile: C:\Users\carlos\AppData\Local\Temp\32499A8F-174C-47C6-8EE5-093A98412366\f15479264.jpg dstDir 2012 - Berlin dstFn f15479264.jpg type ORIG_FILE pos LAST size 551737 --> timeout 30
17:17:25, DEBUG: uploadPictureFile: LrHttp.post(https://mynas.com/photo/include/asst_file_upload.php, timeout: 30, fileSize: 551737
17:17:25, DEBUG: postHeaders:
17:17:25, DEBUG: Field: Content-Type Value: image/jpeg
17:17:25, DEBUG: Field: X-PATH Value: 2012%20%2D%20Berlin
17:17:25, DEBUG: Field: X-DUPLICATE Value: OVERWRITE
17:17:25, DEBUG: Field: X-ORIG-FNAME Value: f15479264%2Ejpg
17:17:25, DEBUG: Field: X-UPLOAD-TYPE Value: ORIG_FILE
17:17:25, DEBUG: Field: X-IS-BATCH-LAST-FILE Value: 1
17:17:25, DEBUG: Field: X-LAST-MODIFIED-TIME Value: 1353499098
17:17:26, DEBUG: Got Body:
{"success":true,"err_msg":"","duplicate_folder":false}
17:17:26, INFO : Upload of "f15479264.jpg" to "2012 - Berlin" done
17:17:26, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\32499A8F-174C-47C6-8EE5-093A98412366\20121121_231205.jpg

**Comment by limaco** [comment]
![2016-05-03_17-22-58](https://cloud.githubusercontent.com/assets/6970073/14990290/ce583624-1153-11e6-9643-117f9ea0f1c1.jpg)

**Comment by flingo64** [comment]
I need more info:
- Lightroom version
- plugin version
- was the published collection already published with an older version (< 5.0) of the plugin? If so, did you convert the photos to 5.0 format?

**Comment by limaco** [comment]
Hello

It was a clean installation of the last version of the plugin (5.5.0), on a windows 10 machine, LightRoom CC 6.5, PhotoStation Uploader v.1.3.0.56.

Export is OK, problem arises when publishing.

17:14:48, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\20121120_201751.jpg
17:14:48, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:48, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\20121120_201751.jpg, jpg,Flat 2012 - Berlin)
    returns 20121120_201751.jpg 2012 - Berlin/20121120_201751.jpg
17:14:48, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/20121120_201751.jpg"
17:14:48, DEBUG: existsPic: dstFilename 2012 - Berlin/20121120_201751.jpg --> dstDir 2012 - Berlin
17:14:48, INFO : CheckExisting: No upload needed for "20121120_201751.jpg" to "2012 - Berlin/20121120_201751.jpg" 
17:14:49, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\f13000704.jpg
17:14:50, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:50, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\f13000704.jpg, jpg,Flat 2012 - Berlin)
    returns f13000704.jpg 2012 - Berlin/f13000704.jpg
17:14:50, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/f13000704.jpg"
17:14:50, DEBUG: existsPic: dstFilename 2012 - Berlin/f13000704.jpg --> dstDir 2012 - Berlin
17:14:50, INFO : CheckExisting: No upload needed for "f13000704.jpg" to "2012 - Berlin/f13000704.jpg" 
17:14:50, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\f15483800.jpg
17:14:51, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:51, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\f15483800.jpg, jpg,Flat 2012 - Berlin)
    returns f15483800.jpg 2012 - Berlin/f15483800.jpg
17:14:51, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/f15483800.jpg"
17:14:51, DEBUG: existsPic: dstFilename 2012 - Berlin/f15483800.jpg --> dstDir 2012 - Berlin
17:14:51, INFO : CheckExisting: No upload needed for "f15483800.jpg" to "2012 - Berlin/f15483800.jpg" 
17:14:51, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\f15479264.jpg
17:14:52, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:52, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\f15479264.jpg, jpg,Flat 2012 - Berlin)
    returns f15479264.jpg 2012 - Berlin/f15479264.jpg
17:14:52, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/f15479264.jpg"
17:14:52, DEBUG: existsPic: dstFilename 2012 - Berlin/f15479264.jpg --> dstDir 2012 - Berlin
17:14:52, INFO : CheckExisting: No upload needed for "f15479264.jpg" to "2012 - Berlin/f15479264.jpg" 
17:14:52, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\20121121_231205.jpg
17:14:52, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:52, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\20121121_231205.jpg, jpg,Flat 2012 - Berlin)
    returns 20121121_231205.jpg 2012 - Berlin/20121121_231205.jpg
17:14:52, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/20121121_231205.jpg"
17:14:52, DEBUG: existsPic: dstFilename 2012 - Berlin/20121121_231205.jpg --> dstDir 2012 - Berlin
17:14:52, INFO : CheckExisting: No upload needed for "20121121_231205.jpg" to "2012 - Berlin/20121121_231205.jpg" 
17:14:52, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\20121122_115403.jpg
17:14:53, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:53, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\20121122_115403.jpg, jpg,Flat 2012 - Berlin)
    returns 20121122_115403.jpg 2012 - Berlin/20121122_115403.jpg
17:14:53, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/20121122_115403.jpg"
17:14:53, DEBUG: existsPic: dstFilename 2012 - Berlin/20121122_115403.jpg --> dstDir 2012 - Berlin
17:14:53, INFO : CheckExisting: No upload needed for "20121122_115403.jpg" to "2012 - Berlin/20121122_115403.jpg" 
17:14:53, TRACE: Next photo: C:\Users\carlos\AppData\Local\Temp\1083F7DA-0BD6-4FE4-B520-B79B76C53B39\20121122_213821.jpg
17:14:53, DEBUG:   sanitized dstRoot: 2012 - Berlin
17:14:53, TRACE: getPublishPath(D:\Carlos\Imágenes\Lightroom\Pictures\2012\11\20121122_213821.jpg, jpg,Flat 2012 - Berlin)
    returns 20121122_213821.jpg 2012 - Berlin/20121122_213821.jpg
17:14:53, TRACE: Old publishedPhotoId: <Nil>,  New publishedPhotoId: 2012 - Berlin/20121122_213821.jpg"

**Comment by limaco** [comment]
[Full log.txt](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/247545/Full.log.txt)

**Comment by limaco** [comment]
Seems to be an issue in PSPublishSupport.lua, that said from my complete ignorance

**Comment by flingo64** [comment]
Sorry, I have no clue what is going on there! There is only one place where I use the recordPublishedPhotoUrl() and that's exactly one line after the call of recordPublishedPhotoId(). Either the Lr message is complete nonsense, or I'm totally blind.

Could you please add one line of code (writeLogfile(...) ) in PSUploadTask.lua after line 419, so it looks like this:
```
local function ackRendition(rendition, publishedPhotoId, publishedCollectionId)
	writeLogfile(4, string.format("ackRendition('%s', '%s')\n", ifnil(publishedPhotoId, 'nil'), ifnil(publishedCollectionId, 'nil')))
	rendition:recordPublishedPhotoId(publishedPhotoId)
	-- store a backlink to the containing Published Collection: we need it in some hooks in PSPublishSupport.lua
	rendition:recordPublishedPhotoUrl(tostring(publishedCollectionId) .. '/' .. tostring(LrDate.currentTime()))
	return true
end
```
reload the plugin or restart Lr afterwards. Please send me the log (DEBUG) when error occurs.

Martin

**Comment by limaco** [comment]
Log mod does not register anything when the error window pops out.

It appears, although, when there is  no error.

[log.txt](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/247829/log.txt)
![2016-05-03_22-47-01](https://cloud.githubusercontent.com/assets/6970073/14999437/39169762-1181-11e6-9628-f67b9a19e2a7.jpg)

**Comment by flingo64** [comment]
That was a hard one!!!
Thanks to Google and Rob Cole I found this description:
https://feedback.photoshop.com/photoshop_family/topics[/lightroom_sdk_rendition_recordpublishedphotoid_url](url)
This means, you'll get this error when you publish 2 photos with the same remote id. Since the remote id is the remote path in this plugin, it means you are publishing two different photos to the same target album. In fact, I found your duplicates:
```
	Line 577: 22:41:28, DEBUG: ackRendition('Test/20120101_090112.jpg', '1177709')
	Line 642: 22:41:30, DEBUG: ackRendition('Test/20120101_090112.jpg', '1177709')

```
Unfortunately, the popup messages seems to happen completely unrelated to what is going on in the logfile.

I will do some more testing to see if this is really the cause, but it seems to be. Can you confirm the duplicates?

**Comment by limaco** [comment]
Hello again and thank you for your time

There where some photos with the same name, indeed. Not exactly duplicates, but edited copies. One of them (in this example, many in thehole tree) seems to lack the field [-Image Unique ID], maybe hence the problem? I don't know. Attached to this comment you will find the .diff between the metadata.

Congratulations by this nice piece of software, btw!

[prueba.zip](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/248531/prueba.zip)

**Comment by flingo64** [comment]
The Remote-Id is required to reference a photo in its target. Photo StatLr uses just the target pathname of the photo. If two photos go to the same target, it will conflict in two places:

- the photos will overwrite each others in Photo Station (the last published photo survives)
- recordPublishedPhotoId() won't work, but that method has no treatable return code, so the following recordPublishedPhotoUrl() will raise the exception

In your case the metadata information of a photo is not taken into account when defining the Remote-Id. If you would use a target album defintion that includes metadata placeholders (see wiki), then parts of the album pathname (but not the photo filename in the target) are derived from that metadata.

**Comment by limaco** [comment]
I assumed the problem came by the files sharing the name, even if they are not the same photo. Just used duplicates finder plug-in and renamed some selected edited photos, working smoothly now.

**Comment by flingo64** [comment]
Exactly: files sharing the same filename  published to the same target album won't work.
