### ISSUE TITLE
Published photos are immediately marked for republish

### ISSUE THREAD

**Issue by svenwiegand** [flingo64/PhotoStation-Upload-Lr-Plugin#16]
At first: Many thanks for providing this great plugin! I have a Synology DS since a week and now started to publish all my lightroom photos (~10,000) to photo station via your plugin.

I've created a published smart collection which includes all photos not marked for dismissed and with a date newer than `x`. Where I started with `x >= 2016-01-01` and after this export was done continued with `x >= 2015-01-01` and so on. My goal was have smaller publishing chungs and to publish the newest photos first.

Everything works fine accept the fact, that when I publish a year, each photo which is published for the first time is immediately marked for republishing. I can see this in the collection view: As soon as the "New photos to be published" counter is decreased by one, the "Photos to be republished counter is increased". Thus effectively I need to publish each photo twice which which is quite time consuming at ~5 seconds per photo.

Any ideas, what could cause this problem?

BTW: I'm using the latest 5.x version of your plugin in Lightroom 6 on Windows 10 64 Bit.

**Comment by flingo64** [comment]
Hmm,
that's strange! I'm using Lr 6.7 on Win10 also, never saw this happening.
First of all, here is a work-around to avoid the second upload: use "CheckExisting" as Publish mode for the second round, that's much faster.

Now back to the issue: it sounds as if the upload triggers some metadata change in the original photo, in which case Lr will set the photo to "Modified to Re-publish"
Could you post a screenshot of the Smart-Collection settings (I'm not sure what you mean w/ 'not marked for dismissed', is it the black reject flag) . Also, a logfile extract (Loglevel Debug) of an successful upload may help. 
Martin

**Comment by flingo64** [comment]
Please check this post and the link in it to the Adobe forum if this might be the reason:
http://www.synology-forum.de/showthread.html?62754-Lightroom-Export-Plugin-PhotoStation-Upload/page41&p=659283&viewfull=1#post659283

**Comment by svenwiegand** [comment]
Thanks for the quick response Martin. I think I've found the cause of the immediate republishing: I'm using Lightroom since its first version. So most of my older Photos have been processed with older Lightroom versions. In 2012 Adobe changed the processing engine and it looks as converting old images to the new processing settings causes the related images to be marked as modified. And this conversion seems to automatically happen on export and thus each exported image is immediately modified.

To avoid this, I simply need to migrate the photos' processing settings before publishing them: Simply select all the images to publish and choose "Entwicklungseinstellungen > Auf aktuellen Prozess aktualisieren (2012)"

Now images are only published once.

**Comment by flingo64** [comment]
Good to know!
Thnx, Martin
