### ISSUE TITLE
Feature-Request: Exclude photos hidden in stack

### ISSUE THREAD

**Issue by svenwiegand** [flingo64/PhotoStation-Upload-Lr-Plugin#18]
I'm often using stacks to bundle multiple related photos and put the best of them on top of the stack. At least some export plugins (used "rc Tree Sync" until now) provide the option to "Ignore photos buried in stack". Such an option would be great in phtostat-lr too :-)

**Comment by flingo64** [comment]
The stack feature was been discussed in the [Synoloy Forum](https://forum.synology.com/enu/viewtopic.php?f=17&t=96477&p=444946&hilit=lightroom+stack#p444879) before.
My last statetement can be found [here](https://forum.synology.com/enu/viewtopic.php?f=17&t=96477&p=444946&hilit=lightroom+stack#p444879).

I agree I would be a cool feature but still not convinced it should be done in the plugin. It would work in Export but in Publish mode there is no way to be informed when a stack membership/position changes, so it's likely to get unsynched changes, which will lead to complaints about Photo StatLr. 

What about a feature request to Adobe: stack membership/position as a filter criteria?

**Comment by svenwiegand** [comment]
Okay, Understand the problem. Thanks for explanation.

**Comment by flingo64** [comment]
v6.2.0 offers a way to achieve this. If you change the collection setting 
`Rename To: {LrFM:fileName (.+)%..+}{LrRM:stackPositionInFolder ^1([^%d]*)$|?}`
then any photo burried in a stack will be assigned an invalid remote filename such as 'img_123?.jpg' and thus will not be uploaded and stay as "New photo to Publish"

Well, I didn't say it's as simple as with 'rc Tree Sync' but it's doable!
;-) Martin

**Comment by svenwiegand** [comment]
Thanks for the tip. But I'll stay without it to keep my "New to publish" section clean.

Nevertheless: Thanks for this great plugin!

**Comment by flingo64** [comment]
Thanks for the feedback!
Yeah, that's what I do, too: keep the collections clean.

Anyway, it's at least a way to identify thoses photos (probably the only way in Lr). After identifying those photos one could tag them (e.g. white label) and exclude photos with that tag from the Publish Smart Collection, so they get kicked off the collection.

Just wanted to mention it, closing the issue anyway. ;-)
