### ISSUE TITLE
Problem with Photo Station 6.7

### ISSUE THREAD

**Issue by aukedejong** [flingo64/PhotoStation-Upload-Lr-Plugin#19]
Hi,
I just found your plugin and having problems to get it work.
I think it has to do with the Photo Station version 6.7. Can you confirm this and are you planning to fix this?

Thanks
Greetings Auke

The error from the log:
21:14:01, ERROR: Initialization of Standard Photo Station  at
https://192.168.1.4
failed!
Reason: ErrorCode: -1202
21:14:01, INFO : Photo StatLr: Publish failed!: Initialization of Standard Photo Station  at
https://192.168.1.4
failed!
Reason: ErrorCode: -1202

**Comment by flingo64** [comment]
I'm using Photo Station 6.7 and it works all well.
Most likely, the error is related to the server certificate. Please, try with http:  , set the loglevel to "Debug" and consult the logfile for additional info.

**Comment by aukedejong** [comment]
You're right, http works.
Thanks for your fast reply.
