### ISSUE TITLE
Feature request: Synchronization of color labels between Lr and PS Public Shared Albums 

### ISSUE THREAD

**Issue by flingo64** [flingo64/PhotoStation-Upload-Lr-Plugin#22]
See project 'Synchronization of color labels between Lr and PS Public Shared Albums'

**Comment by danielbierstedt** [comment]
Thank you for taking that into account. I'm not a developer, but I'll be more than happy to help.

**Comment by flingo64** [comment]
I started some discussions in the project. Feedback would be welcome.

**Comment by flingo64** [comment]
Project is discontinued.
