### ISSUE TITLE
LrFM:folderName produces album titles with extension

### ISSUE THREAD

**Issue by svenwiegand** [flingo64/PhotoStation-Upload-Lr-Plugin#23]
Thanks again for your plugin which I'm using permanently. But I've encountered one issue: 

- As target album I've specified `{Date %Y}/{LrFM:folderName}`
- When I have folders in Lightroom which contain photos from multiple sources (e.g. my DSLR, compact camera and Galaxy S7) PhotoStatLR will create multiple albums for these folders in the PhotoStation:
  - `<folderName>.dng` for photos from my DSLR
  - `<folderName>.jpg` for photos from my compact camera
  - `<folderName>.JPG` for photos from my Galaxy S7

Whant I want indeed is one album which contains all the photos which are in the folder -- no matter of the source they are coming from. Any ideas?

**Comment by flingo64** [comment]
Hi Sven,
this issue should be fixed in v6.2.1
[https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/releases/tag/v6.2.2](url)

**Comment by svenwiegand** [comment]
Thanks the lot. I'll try the new version.
