### ISSUE TITLE
Support for Publish Collections name/path in metadata placeholders

### ISSUE THREAD

**Issue by filipkis** [flingo64/PhotoStation-Upload-Lr-Plugin#26]
Currently it's possible with {LrCC:name} to select a the standard collection set to be used when exporting. 

What would be beneficial is if I could alternatively select a published collection name (which in my case is the name of the album in Photo Studio and is different from how I organise standard collections in Lightroom) and rename the files according to the name of the published collection.

**Comment by flingo64** [comment]
Added in v6.5.0 as contibuted by you.
