### ISSUE TITLE
Plugin does not work with Lightroom Classic CC (7.0.1)

### ISSUE THREAD

**Issue by AndreasSchumacher** [flingo64/PhotoStation-Upload-Lr-Plugin#28]
Hi,

After Upgrading to Classic CC the plugin doesn't work anymore (see screenshot) :-(

If you need further information I will be pleased to provide them.

![grafik](https://user-images.githubusercontent.com/33359633/32395345-02476066-c0e1-11e7-8c3e-31cac3d2ff2e.png)

**Comment by flingo64** [comment]
Sorry, can't help you on Lr 7.x .
But I can see quite a  lot (> 100) Lr 7.0 installations using the plugin, so there seems to be no general show stopper.  Did you try to re-install the plugin via Lr Plugin Manager?

**Comment by AndreasSchumacher** [comment]
Thanks, that did the trick :-)
