### ISSUE TITLE
Make parameters of sharpening configurable

### ISSUE THREAD

**Issue by sebschub** [flingo64/PhotoStation-Upload-Lr-Plugin#3]
For my taste, the sharpening is a bit too intensive. The parameter `-unsharp 0.5x0.5+0.5+0.008` from [here](http://photo.stackexchange.com/questions/5133/) works better for me. Since this is obviously a matter of taste, making it configurable seems like a good idea. Here, offering two or three settings (low, medium, high) might suffice.

**Comment by flingo64** [comment]
Could you come up with 3 reasonable parameter sets for low, medium and high, where the current plugin settings would be "medium /default"?

**Comment by sebschub** [comment]
Following the explanation posted above, I would not change the radius leaving amount and threshold for modification. Maybe something like

* low: `-unsharp 0.5x0.5+0.5+0.008`
* medium: `-unsharp 0.5x0.5+1.25+0.0`
* high: `-unsharp 0.5x0.5+2.0+0.0`

would make sense? It might be nice to tell the user that these setting do not correspond to the usual LR settings.

**Comment by flingo64** [comment]
OK. I will test it and integrate it in 2 weeks.

**Comment by flingo64** [comment]
Configurable thumbnail sharpening is implemented in v3.2.0.
Check it out, please!

**Comment by flingo64** [comment]
No complaints, closing the issue!
