### ISSUE TITLE
It takes very long to delete a Photo from my Catalog

### ISSUE THREAD

**Issue by DjangoBlok** [flingo64/PhotoStation-Upload-Lr-Plugin#30]
With Photo StatLr it takes very long to delete a Photo from my Catalog.
After I select remove from service, it takes minutes per photo.

**Comment by flingo64** [comment]
Please, send me a logfile with Loglevel DEBUG

**Comment by DjangoBlok** [comment]
Just deleted 11 photos.
Here is the log file, and the screenshots of the message windows.



2017-12-28 0:54 GMT+01:00 Martin <notifications@github.com>:

**Comment by flingo64** [comment]
I don't see the logfile...

**Comment by DjangoBlok** [comment]
I replied by mail, but probably it was filtered out by Github?
[PhotoStatLr - deleted 11 photos.log](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/1592236/PhotoStatLr.-.deleted.11.photos.log)
![2017-12-28_213957](https://user-images.githubusercontent.com/34900082/34424803-b3c9c91c-ec26-11e7-8496-517b916c6aa5.png)
![2017-12-28_214054](https://user-images.githubusercontent.com/34900082/34424804-b3dd83c6-ec26-11e7-9a6f-084ec49663ef.png)
![2017-12-28_214414](https://user-images.githubusercontent.com/34900082/34424805-b3f17c5a-ec26-11e7-81b4-0c4bb8743f81.png)

**Comment by flingo64** [comment]
The deletion of the photos in Photo Station takes approx.  2-3 seconds per photo on your systems which isn't quite fast, but OK. But there seems to be a constant 15 second delay or timeout  in the Lr-related cleanup code.  Just to compare: deleting photos including all Lr related cleanup takes less than a second /photo on my system.

It's either the search for the srcPhoto object: `(PSLrUtilities.getPublishedPhotoByRemoteId(publishedCollection, photoId)) `
or the fetching of the plugin metadata for the belonging shared albums: `PSLrUtilities.getPhotoPluginMetaLinkedSharedAlbums(srcPhoto)`

Question: how many photo are there in your Published Collection (my collections are aroound 2000 to 4000 photos)

Can you add a writeLogfile in file PSLrUtilities.lua after line 783, so it looks like:
```
function PSLrUtilities.getPhotoPluginMetaLinkedSharedAlbums(srcPhoto)
    writeLogfile(3, string.format("getPhotoPluginMetaLinkedSharedAlbums(%s): starting ...\n", srcPhoto:getRawMetadata('path'))
    local sharedAlbumPluginMetadata = srcPhoto:getPropertyForPlugin(_PLUGIN, 'sharedAlbums', nil, true)
```
This will help to identify the exact cause of the delay in the logfile.

**Comment by flingo64** [comment]
Please replace th whole function iin PSLrUtilities.lua after line 783 ff by this:
```
function PSLrUtilities.getPhotoPluginMetaLinkedSharedAlbums(srcPhoto)
	writeLogfile(3, string.format("getPhotoPluginMetaLinkedSharedAlbums(%s): starting ...\n", srcPhoto:getRawMetadata('path'))
	local sharedAlbumPluginMetadata, error = srcPhoto:getPropertyForPlugin(_PLUGIN, 'sharedAlbums', nil, true)
	local sharedAlbumsPS

	-- format of plugin metadata: <collectionId>:<sharedAlbumName>/{<collectionId>:<sharedAlbumName>}
	if ifnil(sharedAlbumPluginMetadata, '') ~= '' then
		sharedAlbumsPS = split(sharedAlbumPluginMetadata, '/')
	end
	writeLogfile(3, string.format("getPhotoPluginMetaLinkedSharedAlbums(%s): Shared Albums plugin metadata: '%s' / error:'%s'\n", 
									srcPhoto:getRawMetadata('path'), ifnil(sharedAlbumPluginMetadata, ''), ifnil(error, '')))    		
	return sharedAlbumsPS
end 
```
This adds error message output in case the srcPhoto:getPropertyForPlugin() call fails.

**Comment by DjangoBlok** [comment]
The published collection is my complete library (35000 photos)
I think you missed a close parentheses at the second line?
Here is the log file with edited function.
[PhotoStatLr2 - deleted 5 photos.log](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/1594023/PhotoStatLr2.-.deleted.5.photos.log)

**Comment by flingo64** [comment]
So, the linear reverse search for the PublishedPhoto object (getPublishedPhotoByRemoteId()) is the time-eater. Actually, it takes around 7 seconds for my 4000 photos collection (my test from yesterday was dealing with a 20 photos collection).  I can't see a way to speed-up this search, so I'm looking for another approach.
Just for explanation: when a photo is removed from a collection, the plugin wants to clean-up the photo's plugin metadata that holds the list of Photo Station Shared Albums the photo is linked to. The Lr hook deletePhotosFromPublishedCollections() does only submit the remote photo id, but not the Published Photo object, which is required to retrieve the plugin metadata for the photo, so the plugin has to do a reverse search for the object.
So, the probably rarely or never used feature 'Photo Station Shared Album' is slowing down the really basic 'Delete Photo' feature significantly.  That's stupid!

Now, the idea is to remove the cleanup code from deletePhotosFromPublishedCollections() (in most cases the photo will be deleted from the catalag thereafter, anyway) and to add some code that makes sure that a photo newly added to a published collection will not have any garbage in its plugin metadata (it might have been removed from that collection before).

**Comment by DjangoBlok** [comment]
OK, The reverse search sounds strange to me if you already have an ID. At least You seem to be on the right track for a solution?

**Comment by flingo64** [comment]
The remoteID is not the index of the Published Photo object, it's just an attribute holding the remote identification of the photo, i.e. the path in Photo Station where it was published to.

I will work on the solution within the next days.

**Comment by flingo64** [comment]
Version 6.5.3 fixes this issue. Please, retest.

**Comment by DjangoBlok** [comment]
Thanks, yes no lightning speeds, but a lot faster than it was before.
