### ISSUE TITLE
Error -1001 macOS HighSierra 10.13.3

### ISSUE THREAD

**Issue by Gonzo972** [flingo64/PhotoStation-Upload-Lr-Plugin#31]
Hi Flingo,

Before all, great job.

I wonder if I could get help from you because I cannot find information about my error.
During starting of publishing Photo StatLR 6.5.4 pop me up this error "-1001" on macOS 10.13.3 and the last lightroom 2018 version 7.2.

Do you have any information? do you need any other information to analyse this issue?

Please let me know.

**Comment by flingo64** [comment]
Raise the Loglevel to Debug and see what the logfile tells you. If you can't figure what it means, send me the logfile

**Comment by Gonzo972** [comment]
Hi Martin,

Sorry for the delay but after having received your e-mail I was investigating and I Found the problem.

All is about « UNIVERSAL SEARCH » and that was not in the log.

Delaying indexation, all pictures was published without issue.

Perhaps you can bypass indexation during the publish process? If not, it have to be done manually.

Or perhaps that was a known issue…

Anyway it’s a great plugin. Congrats…

Miguel

**Comment by flingo64** [comment]
Hi Miguel,
thanks for investigating the issue!
Are you saying that the plugin will fail with error code 1001 if the USB Search indexing process is running? If so, it's not a known issue until now. I will check this and if it is a reproducable error condition, I'll write an FAQ for it. It might be that they lock the media database during indexing. The media indexing process on the other hand is not an issue and in fact the plugin relys in some way on the media indexing process.
Anyway, I'll check the USB Search thing.
Martin

**Comment by Gonzo972** [comment]
Hi Martin,

That seems to be it. For information externally to the plugin, I’ve noticed that it is Photo station that seems to be unreachable during the indexing process. And actually it may not be a plugin issue. 
Let’s keep in touch. 
Regards,

Miguel

**Comment by flingo64** [comment]
Hi Miguel,
I activated Universal Search on my DS and started indexing the /photo folder. In my case, the Photo Station was accessible and also the plugin did not run into any issues.  I think your observation is valuable and in general it's a good idea to check if the Photo Station is accessible in case the plugin fails. There might be different situations in different environments where the Photo Station service is not available.

I think I close the issue.

**Comment by Gonzo972** [comment]
Hi Martin,

Hum! What’s wrong in my config. I will find it out. Now I switched off Universal search and all thing is all right. 
It’s ok for me. You can close the issue. 

Thanks for all

Cordialement,
Regards,

Miguel
