### ISSUE TITLE
An error occurred while attempting to load this plug-in

### ISSUE THREAD

**Issue by fritzg** [flingo64/PhotoStation-Upload-Lr-Plugin#33]
When I try to install to Lightroom CC classic 7.3, I get the error: "An error occurred while attempting to load this plug-in"
Is it planned to upgrade the plugin to version LR above 7.2?

--
fritzg

**Comment by flingo64** [comment]
I should update the Readme: there are a lot of installations out there for Lr 7.3, 7.3.1, 7.4, 7.5 and even for Lr 8.0.
So, Lr 7.3 or higher should be fine.
