### ISSUE TITLE
Http error: No JSON response data!

### ISSUE THREAD

**Issue by CXN271** [flingo64/PhotoStation-Upload-Lr-Plugin#36]
I've been publishing large folders of 1-2000 images and most work but dozens do not upload at all. Some a remarked "to be republished" and a several are listed as new and never published. I haven't yet found any commonalities among the failures. Some are dng and some are jpg.

Lightroom 6.14 using the standard upload option. Plug-in version 6.7.0.20190210

Also... to update the plugin do I just unzip overtop of the existing folder?

**Comment by flingo64** [comment]
'No JSON response data'  means that the Photo Station does not acknowledge the upload of a photo as expected. Most likely, there is an issue on the Diskstation. Disk space, quota, timeout??? Set Loglevel to Debug and see if the logfile is more specifc on that error. If you cannot figure it out, send me the logfile.

Updating is actually as simple as unzipping the new version to the current plugin dir and re-opening Lr. You may also create a new directory for the new version, if you want to keep the old version..  In that case, you have to disable the old plugin and add the new plugin in Lr Plugin Manager.

**Comment by CXN271** [comment]
I found the error but it doesn't appear to an error with my Diskstation's
config:

Warning: rmdir(/var/services/photo/2010 and
Earlier/@eaDir/[2008-10-09T130042].jpg): *Directory not empty in
/volume1/@appstore/PhotoStation/photo/include/asst_file_upload.php on line
199*

Warning:
rename(/volume1/photo/@eaDir/ASST_PHOTO_UPLOAD_TMP_DIR/ASST_TMP_EA_f5q22jq83c0rtn45nb814qg8v2,/var/services/photo/2010
and Earlier/@eaDir/[2008-10-09T130042].jpg): *Directory not empty in
/volume1/@appstore/PhotoStation/photo/include/asst_file_upload.php on line
205*
{"success":true,"err_msg":"warning: rename tmp EA folder fail:
\/var\/services\/photo\/2010 and
Earlier\/@eaDir\/[2008-10-09T130042].jpg","duplicate_folder":false}
16:49:25, TRACE: JSON-DecodeError: msg=JSON encode/decode package,
txt=can't parse JSON
16:49:25, DEBUG: JSON-DecodeError: loc=

**Comment by flingo64** [comment]
Is the filename of the photo really '[2008-10-09T130042].jpg' ? That would be a bad filename, because of the characters it is a regular expression, which might not work for the renaming performed by the Upload service.. 
Can you try to use a filename without '[' and ']' .

**Comment by flingo64** [comment]
No response. closing the issue.

**Comment by CXN271** [comment]
Apologies, I meant to reply. It was the filename in the end, no issues
since. Thanks!

Corey
