### ISSUE TITLE
Internal plugin error in 6.8.1

### ISSUE THREAD

**Issue by stepman0** [flingo64/PhotoStation-Upload-Lr-Plugin#37]
I updated to version 6.8.1 via Git. My plugin folder is identical to Master (version tag 6.8.1).

When I start Lightroom Classic (version 8.2), the plugin seems to work. I can also edit the settings of my smart collection. 

When going into the settings of the plugin (wanted to check out the new video settings ;-), Lightroom says that an internal error occured in the plugin:
![image](https://user-images.githubusercontent.com/17684034/53679407-a0c87f00-3ccc-11e9-8454-e72129e47001.png)

In "Zusatzmodul-Manager" it states that it cannot open the plugin directory:
![image](https://user-images.githubusercontent.com/17684034/53679411-c48bc500-3ccc-11e9-8bd3-aa71be9ad3b3.png)

Any hints?

I tried reloading the plugin, this does not change the behaviour.

**Comment by flingo64** [comment]
I get the same error when the field for the video presets file (scroll down in Plugin Manager) is left empty. Just click on 'Default' in the ffmpeg' group its Plugin Manager section.

**Comment by stepman0** [comment]
Thanks, this helped.
