### ISSUE TITLE
Reduce Framerate of video

### ISSUE THREAD

**Issue by stepman0** [flingo64/PhotoStation-Upload-Lr-Plugin#39]
My camera (mobile phone) records videos with 60 fps. I want to reduce the framerate to 30 fps for the preview videos (to save bandwidth while streaming over the internet). This can be achieved by adding "-r 30" to the conversion parameters.

But: Some of my videos are filmed with 25 fps, this bitrate should not be changed.

Question: In the plugin, do you already read the framerate of the video? I could not find any function.

**Comment by flingo64** [comment]
The fps is currently not determined by the plugin. If required, it should be done in 
PSConvert.ffmpegGetAdditionalInfo(), line 327 by adding another capture to the regexp.
Anyway, how would you proceed with that information?

**Comment by flingo64** [comment]
Version 6.8.x supports user-configurable video conversion presets.

**Comment by stepman0** [comment]
Sorry I missed to answer.

I have videos from my smartphone with 60 fps. To save bandwith, I want to reduce it to 30 fps for these videos. But others, which have for example 25 fps should stay unchanged. Therefore I would try to add a "Max fps" function, which reduces fps if above. 

Just an idea - nothing really urgent...
