### ISSUE TITLE
Videos are not published

### ISSUE THREAD

**Issue by stepman0** [flingo64/PhotoStation-Upload-Lr-Plugin#40]
This plugin works very well and I am exporting pictures and videos - but suddenly video export stopped working. I am on the latest version of Lightroom CC and this plugin. My photos export normally. My publishing job only has a few videos left - if I start publishing, within 2 seconds Lightroom says 0 of 21 exported.

The logfile shows no error messages - I can only see that exiftool is still running in task manager (2 times). 

Any advise?

**Comment by flingo64** [comment]
If the video files are logged in the logfile, rasing the loglevel to DEBUG will give more details.
If the video files do not show up in the logfile at all, it might be an issue with the Lr settings in the 'video' section in the Publish Service  or a filter plugin may be skipping the video .  I have seen this with Metadata Wrangler when exporting -avi videos.

**Comment by stepman0** [comment]
I deactivated all plugins excep PhotoStation Upload.

The video files show up in logfile, but neither Debug nor X-Debug gives me any idea, what is wrong.

I appended 2 logfiles, in both cases I opened Lightroom, startet a publish with 22 outstanding videos, it showed 0 of 22 and I closed Lightroom. The logfile ended with the exiftool command.


[PhotoStatLr-X-Debug.log](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/3218353/PhotoStatLr-X-Debug.log)
[PhotoStatLr-Debug.log](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/files/3218354/PhotoStatLr-Debug.log)

**Comment by flingo64** [comment]
The videos are not delivered to Photo StatLr, otherwise you would see  a line like
22:22:48, TRACE: Next photo: ...
immediately after the first exiftool line (22:22:47, INFO : exiftool Listener(""C:/Windows/exiftool.exe" -config ...)

There might be an issue when publishing videos from an external drive ('"srcRoot":"\\diskstation\photo_orig\2019"'), if have me file on a local drive, so I cant't tell yo u for sure, or probably a disk full situation on the local C: drive (files to be published are copied by Lr to the local TEMP dir before passing them to the publish module).

**Comment by stepman0** [comment]
Thanks for this hints. I made some further checks. It is not related to the external drive - I have the same behaviour if I copy the source to my local disk.

BUT: I use the Lightroom video export setting "Original, unbearbeitete Datei". In this settings, this issue occurs. If I change the export setting to "H.264 Max", the export works!

So this is probably a bug in Lightroom. I will try reproducing it with a new clean catalog.

**Comment by stepman0** [comment]
I can reproduce it with an empty catalog. Export original videos without transcoding by Lightroom does not work in current version (8.2.1). I am still searching for a possibility to downgrade.

So this is not an issue with your plugin. 

Could you maybe test - if you have the same issue?

**Comment by flingo64** [comment]
I use Lr 6.14 and I'm exporting videos as Original, no issue there. 
Did you try to export videos with another Export plugin such as HDD Export?

**Comment by stepman0** [comment]
Problem was solved with todays update of Lightroom CC (to version 8.3.1). Thanks for your help!
