### ISSUE TITLE
Video doesn't get rotated on 'Rotate-xy' and hard rotation

### ISSUE THREAD

**Issue by SuperMasterPhoenix** [flingo64/PhotoStation-Upload-Lr-Plugin#42]
Hi,

I am having issues exporting my videos when using the Rotate-xy keywords and the hard rotate checkbox checked. The videos don't get rotated at all.

Using ffmpeg 4.2.1 Photo StatLR creates the following command for the video conversion:
`"C:/Program Files (x86)/Synology/Photo Station Uploader/ffmpeg/ffmpeg.exe" -noautorotate  -i "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115.mp4" -y -vf "transpose=2" -metadata:s:v:0 rotate=0 -strict experimental -acodec aac -ar 44100 -b:a 64k -ac 2 -vf format=yuv420p -c:v libx264 -preset medium -crf 23 -s 720x1280 -aspect 720:1280 -metadata creation_time="2019-10-17 14:11:55"  -passlogfile "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115_MED_TMP.passlog" "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115_MED_TMP.mp4"`

which leads to an error message from ffmpeg:
`Only '-vf format=yuv420p' read, ignoring remaining -vf options: Use ',' to separate filters
Only '-af (null)' read, ignoring remaining -af options: Use ',' to separate filters`

When I manually adapt the command to the following one:
`"C:/Program Files (x86)/Synology/Photo Station Uploader/ffmpeg/ffmpeg.exe" -noautorotate  -i "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115.mp4" -y -metadata:s:v:0 rotate=0 -strict experimental -acodec aac -ar 44100 -b:a 64k -ac 2 -vf format=yuv420p,transpose=2 -c:v libx264 -preset medium -crf 23 -s 720x1280 -aspect 720:1280 -metadata creation_time="2019-10-17 14:11:55"  -passlogfile "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115_MED_TMP.passlog" "C:\Users\mike\AppData\Local\Temp\737D91E1-7C5F-49E1-9A2C-D717934BAA1D\20191017_161115_MED_TMP.mp4"`
the video get created as expected (rotated).

ffmpeg doesn't like the duplicated parameter '-vf' which is unfortunately created when using the rotate functionality.

It would be great if you could fix this :-)

Thanks for this really great software,
Mike

**Comment by flingo64** [comment]
Hi Mike,
thanks for reporting the issue. Video hard-rotation was broken by the introduction of video conversion presets (V6.8.0). I fixed it in V6.8.6 by introducing a new mandatory video conversion preset attribute (video_filters) which now takes the -vf option, which was previously included in the video_options attribute.  In that way I could rearrange the ffmpeg command line to not duplicate the -vf option.

Please check out [V6.8.6](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/releases/tag/v6.8.6).
Martin

**Comment by SuperMasterPhoenix** [comment]
Hi Martin,
thank you for your fast response and fix. The videos now get exported as expected.

Now that the rotation is working I encountered another (minor) problem, but I'll open a new issue for it.

Mike
