### ISSUE TITLE
recordPublishedPhotoUrl must be called after recordPublishedPhotoId

### ISSUE THREAD

**Issue by besule** [flingo64/PhotoStation-Upload-Lr-Plugin#44]
Hi,

on some photos i get these exception presented (see photo). My problem is, that it stops the execution of the publish. Could you reroute the message to the log, so the export does not pause?
I checked the "PhotoStatLr.log". No info added there at the moment.

![exception](https://user-images.githubusercontent.com/64862911/81100723-4e58a300-8f0d-11ea-94f1-810ffc63a207.png)

**Comment by flingo64** [comment]
The issue is described in [this doc](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/Documentation/22-Error-Publish-recordPublishedPhotoUrl%20-%20must%20be%20called%20after%20recordPublishedPhotoId.md). Unfortunately, one cannot catch this exception.
