### ISSUE TITLE
Is it possible?

### ISSUE THREAD

**Issue by tedserreyn** [flingo64/PhotoStation-Upload-Lr-Plugin#5]
Sorry to open this as an issue, I don't see an email anywhere to contact you directly.

Is it possible to use this upload/publish plugin to keep a local photo archive by YYYY/MM/DD in sync with the same photo albums on a photo station?

Ok is it possible to do to two photo stations (one local, one DR/datacenter)?

Ted Serreyn
ted@serreyn.com

**Comment by flingo64** [comment]
Hi Ted,
yes, this is exactly what the Publish funcitionality of the plugin aims at. Sync is done via the Lr "Publish" mechanisms with the following limitations:
- synch is always one-way: Lr -->PS
- you may sync developed or original photos, but be aware that only jpg and Lr's version of DNG is really tested and supported by the plugin. Some RAW file formats are currently under investigation, but no guaranty that they will be supported within future releases (pretty sure, it will come, but don't blame me if not)
- working with different/multiple PhotoStations can easily be achieved by defining different  Publish Providers in Lr.

You may also want to read the Readme (RTFM ;-) ) or follow this thread:
http://forum.synology.com/enu/viewtopic.php?f=17&t=96477

Regards, Martin

**Comment by flingo64** [comment]
I guess the question was answered
