### ISSUE TITLE
Patterns for matching Ratings and ColorLabels match other tags 

### ISSUE THREAD

**Issue by ftitius** [flingo64/PhotoStation-Upload-Lr-Plugin#51]
In PSPublishSupport.lua lines 1377-1385 patterns were used for matching ratings and color labels which also match tags with a '*' or a '+'  inside their name. Please correct the patterns with a start (^) and end ($) sign:

Existing patterns:

> '([%*]+)'
> '%+(%a+)'
> 

Would be better:

> '^([%*]+)$'
> '^%+(%a+)$'
> 

I found this error because PhotoStat LR always wanted to republished the same photos. Cause where the difference between local and remote tags, because one tag with a '+' inside its name was never recognized as a normal tag.

**Comment by flingo64** [comment]
That was a bad one! It prevented downloading certain tags even if you didn't enable downloading color label tags or rating tags.
It's fixed in v6.9.5

**Comment by ftitius** [comment]
Thanks - works like a charm. Wonderful plugin.
