### ISSUE TITLE
Uploading fails even for old published collection

### ISSUE THREAD

**Issue by mpeter1975** [flingo64/PhotoStation-Upload-Lr-Plugin#54]
I use the plugin as before with no change of LR or Photostation. 
plugin: 6.8.5, LR: 10.2, Photo Station: 6.8.14-3501

Created new published collection in the usual published collection set. Upload fails with this

```
19:29:01, ERROR: PSUploadAPI.uploadPictureFile('C:\Users\mp\AppData\Local\Temp\8F8A6858-0505-4A39-B2D9-5E5A6FC7ABDF\20210530_171002_0363_B.jpg', 'family/2021/2021-05-30 - esztergom', '20210530_171002_0363.jpg') failed: file_size_not_matchwriten file size:0 Content-Length:136145!
19:29:01, ERROR: Upload of 'P:\original\2021\2021-05-30 - esztergom\20210530_171002_0363.NEF' to 'family/2021/2021-05-30 - esztergom/20210530_171002_0363.jpg' failed!!!
```

I marked for republish an old image in an other collection. Re-published and failed again. There is enough space in C and P drive, in Photostation, all folders have RW access.

Update: Plugin was updated to latest (6.9.5) with the same failing result.

Please advise.

**Comment by flingo64** [comment]
The error message 'file_size_not_matchwriten' is returned from the PhotoStation Upload API. It has been [observed by others users](https://www.synology-forum.de/threads/lightroom-export-plugin-photostation-upload.62754/post-778053) in different situations as well.
Unfortunately, it was never nailed down to a specific issue. I would recommend:
- reboot Synology Diskstation 
- if this doesn't solve the issue, make sure the folder  '/volume1/@tmp/photo_upload_tmp_dir' is empty

**Comment by flingo64** [comment]
[This guy wrote ](https://www.synology-forum.de/threads/lightroom-export-plugin-photostation-upload.62754/post-645027)that reinstalling Photo Station solved [the issue](https://www.synology-forum.de/threads/lightroom-export-plugin-photostation-upload.62754/post-644026).

**Comment by mpeter1975** [comment]
Restarting solved the problem, thanks for the help.
