### ISSUE TITLE
Lightroom Classic 11 mit Windows 11

### ISSUE THREAD

**Issue by UweKau** [flingo64/PhotoStation-Upload-Lr-Plugin#58]
Konnte das download-archiv nicht finden und lud die Dateien einzeln herunter.

Das Plugin funktioniert bei mir nicht. Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/104095433/164310947-467270c7-802f-4cde-8759-7b3b1ea691e0.png)
(Dieses Zusatzmodul funktioniert nicht einwandfrei und kann nicht verwendet werden.
Info.lua:7:unexpected symbol near '<'

**Comment by flingo64** [comment]
There is no '<' in line 7 in 
[Info.lua](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/PhotoStation_upload.lrplugin/Info.lua)
Please, check if your [download](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/archive/refs/heads/master.zip) is corrupted.

**Comment by UweKau** [comment]
Thanks, new download was working!
