### ISSUE TITLE
Publish fails when folder name contains an amperstamp '&'

### ISSUE THREAD

**Issue by Thoscellen** [flingo64/PhotoStation-Upload-Lr-Plugin#59]
On Mac OS Monterey

Whenever I have a publish service set up to a Synology Photo app
And I already updated photos to this service
And the option _Tree copied relative to_ contain a path to a folder in my catalog
When I want to upload photos where a sub folder contains `&`
Then the publication is cancelled with an error `Target Album missing`
And no album / folder is created on the NAS

## Workarounds

The user can create the folder beforehand on the NAS (at the location the service will create it), then publish the photo.

Seems to work if the file contains `&`.

## Log:

```
22:10:33, INFO : Environment: plugin: 7.2.0.20220131 Lr: 11.3.1 OS: 12.3.1.21E258 Lang: fr
22:10:33, INFO : processRenderedPhotos starting
22:10:36, INFO : Login to Personal Space of ***
22:10:36, INFO : processRenderedPhotos(mode: Publish).
22:10:36, INFO : --------------------------------------------------------------------
22:10:37, INFO : PSUtilities.deleteAllEmptyFolders: Deleted 0 empty albums.
22:10:37, INFO : --------------------------------------------------------------------
```

**Comment by flingo64** [comment]
Ooh: foldernames were not url-encoded when calling the Photos API.
Is fixed in v7.2.1 (just uploaded)
Thanks for reporting!
