### ISSUE TITLE
Can't delete photos from the published collection

### ISSUE THREAD

**Issue by laurentlagosanto** [flingo64/PhotoStation-Upload-Lr-Plugin#6]
Hi,

I have two pictures in my published collection, that I've already published.
If I delete one of them from the collection (not from lightroom), and I click on publish again, I get an error dialog saying "Internal error: deletePhotosFromPublishedCollection: did not call deletedCallback function"

Here are the items I see in the log:

23:18:15: FileStation Login(https://xyz.synology.me:5001) OK.
23:18:15: Login to Standard PhotoStation(https://xyz.synology.me) OK
23:18:15: processRenderedPhotos(mode: Publish).
23:18:15: --------------------------------------------------------------------
23:18:17: Create dir - parent:  newDir: LR_Delete newPath: /LR_Delete
23:18:22: Upload of "DSC_0286.jpg" to "LR_Delete" done
23:18:26: Upload of "DSC_0287.jpg" to "LR_Delete" done
23:18:26: --------------------------------------------------------------------
23:18:26: PhotoStation Upload: Uploaded 2 of 2 files in 11 seconds (5.6 secs/pic).

23:19:45: initializeEnv starting:
23:19:46: FileStation Login(https://xyz.synology.me:5001) OK.
23:19:46: Login to Standard PhotoStation(https://xyz.synology.me) OK
23:19:46: deletePhotosFromPublishedCollection:  "LR_Delete/DSC_0287.jpg"
23:19:46: deletePhotosFromPublishedCollection:  "LR_Delete/DSC_0287.jpg" failed!

Please note that:
1. I have checked that the user I logged with is actually able to delete photos
2. I see no trace of a delete request in the photostation log

my environment is:
Synology Photo Station 6.3-2954
PhotoStation-Upload-Lr-Plugin 3.3.2.20150904
Lr: 6.1.1 
OS: Windows 8.1 Home Premium Edition
Lang: fr

Let me know if you wantme to give more details or make some tests.

**Comment by flingo64** [comment]
Could you please set the loglevel to "Debug" and re-test.

**Comment by laurentlagosanto** [comment]
Sure, here it is:

10:04:19: FileStation Login(https://xyz.synology.me:5001) OK.
10:04:19: login: LrHttp.post(https://xyz.synology.me/photo/webapi/auth.php,...)
10:04:19: Got Body:

{"success":true,"data":{"sid":"djvnshc1v40l3rt4he5ng62p34","username":"laurent","reg_syno_user":true,"is_admin":true,"allow_comment":false,"permission":{"browse":true,"upload":true,"manage":true},"enable_face_recog":false,"allow_public_share":true}}

10:04:19: Login to Standard PhotoStation(https://xyz.synology.me) OK
10:04:19: deletePhotosFromPublishedCollection:  "LR_Delete/DSC_0287.jpg"
10:04:19: deletePic: LrHttp.post(https://xyz.synology.me:5001/webapi/FileStation/file_delete.cgi, api=SYNO.FileStation.Delete&version=1&method=delete&path=/photo/LR_Delete/DSC_0287.jpg)
10:04:19: Got Body:
{"error":{"code":900,"errors":[{"code":407,"path":"/photo/LR_Delete/DSC_0287.jpg"}]},"success":false}

10:04:19: deletePhotosFromPublishedCollection:  "LR_Delete/DSC_0287.jpg" failed!
10:04:19: closeSession(Delete):...
10:04:19: closeSession(Delete) done.

**Comment by flingo64** [comment]
Hi,
- {"error":{"code":900,"errors":[{"code":407,"path":"/photo/LR_Delete/DSC_0287.jpg"}]},"success":false}

can be decode according to :
- http://global.download.synology.com/download/Document/DeveloperGuide/Synology_File_Station_API_Guide.pdf 
    - page 87: code 900: --> failed to delete file(s)/folder(s). More information in <errors> object
    - page 9: error 407 --> Operation not permitted

It's definitely a permission issue. The thing is, that due to missing API documenation the plugin uses 2 APIs that work on probably different user accounts / permissions: the PhotoStation Upload API and the FileStation API (which is used for delete). So, you may be able to delete a photo in PhotoStation, but not via FileStation. Please, check you can delete the file via the FileStation (or probable via fiel share connection to /photo share) using the configured account and see if it works or if you can adjust permissions accordingly. Otherwise, you may also configure a different account for the FileStation API.

Martin

**Comment by laurentlagosanto** [comment]
Ok. So I guess you're trying to delete the file from the /photo/.... folder, so that won't work because /photo is an admin folder and even though the user "Laurent" is an admin user, the /photo folder is not even exposed via filestation (except for the admin user himself).

That lead me to the idea that maybe another workaround would be to enable "Personal Photo Station", which indeed worked perfectly.

**Comment by flingo64** [comment]
I wasn't aware that access to /photo is restricted to admin. I'm pretty sure that I can drop photos in the /photo share of my diskstation using my non-administrative account. I'll check that later. 

Anyway, Personal PhotoStation is an alternative, but I'm not sure if the Mediaserver (for DLNA clients) sees those folders?

**Comment by laurentlagosanto** [comment]
To be able to drop photos into the /photo share as a user, you need to make /photo read/write for this user.

The MediaServer doesn't see the Personal PhotoStation folders

**Comment by flingo64** [comment]
You're right, /photo is by default only rw by admin! So, it's a good idea to make this requirement clear. 
For now, I clarified the requirements for the specific Publish features in the Readme (hoping, somebody reads it).
I 'll add some code to point out specific permission issues later.

**Comment by flingo64** [comment]
Version 3.4.0 gives detailed error messages, not only error codes.
