### ISSUE TITLE
ERROR : getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)

### ISSUE THREAD

**Issue by drissslim** [flingo64/PhotoStation-Upload-Lr-Plugin#65]
Hi,

I'm getting these errors when try to publish video. I'm using DSM 7.1 with Synology Photos and the latest PhotoStation Lr Plugin 7.2.3

getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)

Please could you help on that?
Thank you.

`18:20:47, INFO : Photo StatLr: Publish done: Uploaded 6 of 6 files in 821.0 seconds (136.7 secs/pic).
18:20:48, INFO : Login to Shared Space(https://driss.info:5001) OK
18:20:48, INFO : Get comments: comments not supported/enabled for this collection.
18:20:48, INFO : Get ratings/metadata: options(title: false, caption: false, location: false, locationTag: false rating: false, tags: false, face xlat: false, label xlat: false, rating xlat: false)
18:20:48, INFO : Get ratings/metadata: Metadata download is not enabled for this collection.
18:27:26, INFO : PSInitPlugin:
		convert: '/usr/local/bin/convert'
		dcraw: '/usr/local/bin/dcraw'
		exiftool:   '/usr/local/bin/exiftool'
		ffmpeg:     '/usr/local/bin/ffmpeg'
18:27:26, INFO : PSInitPlugin: Successfully added 2 custom video export presets.
18:27:30, INFO : Environment: plugin: 7.2.3.20220808 Lr: 11.4.1 OS: 11.6.8.20G730 Lang: en
18:27:32, INFO : processRenderedPhotos starting
18:27:33, INFO : Login to Shared Space(https://driss.info:5001) OK
18:27:33, INFO : processRenderedPhotos(mode: Publish).
18:27:33, INFO : --------------------------------------------------------------------
18:29:37, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190202-134759.mp4' to 'Videos/2019/02/20190202-134759.mp4' done
18:31:40, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1096.MP4' to 'Videos/2019/02/20190211-1096.mp4' done
18:32:36, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1097.MP4' to 'Videos/2019/02/20190211-1097.mp4' done
18:32:49, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1098.MP4' to 'Videos/2019/02/20190211-1098.mp4' done
18:39:54, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1099.MP4' to 'Videos/2019/02/20190211-1099.mp4' done
18:48:12, INFO : Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1148.MP4' to 'Videos/2019/02/20190211-1148.mp4' done
19:43:28, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:28, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos/2019/02') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:29, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos/2019/02') returns '<nil>' (after cache update)
19:43:30, ERROR: Photos_listAlbumItems('/Videos/2019/02') could not get folderId, returns <nil>
 is not a table, but nil
19:43:30, ERROR: getPhotoId(userid:0, path:'/Videos/2019/02/20190211-1149.mp4') listFunction('/Videos/2019/02') returned <nil>
19:43:30, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update)
19:43:30, ERROR: getFolderId(userid:0, path '/Videos/2019') returns '<nil>' (after cache update)
19:43:31, ERROR: getFolderId(userid:0, path '/Videos/2019/02') returns '<nil>' (after cache update)
19:43:31, ERROR: Upload of '/Volumes/WD3TB/Videos/2019/02/20190211-1149.MP4' to 'Videos/2019/02/20190211-1149.mp4' failed!!!
19:43:32, ERROR: getFolderId(userid:0, path '/Videos') returns '<nil>' (after cache update and failed folder creation: 803 - No permission to create folder or file)
`

**Comment by flingo64** [comment]
`803 - No permission to create folder or file) `
Check if the account has the permission to create the folder.
Use Loglevel 'Debug' to get more details.

**Comment by flingo64** [comment]
No feedback, closing this issue
