### ISSUE TITLE
exiftool not found on MacOS

### ISSUE THREAD

**Issue by StephenKing** [flingo64/PhotoStation-Upload-Lr-Plugin#7]
Hi,

I've updated my installation to the current state of master. Export fails because `exiftool` cannot be found.

I had to patch the [hardcoded path](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/91315808538975047eebd6f96b48ad2fb0db5c24/PhotoStation_upload.lrplugin/PSExportServiceProvider.lua#L98) to `/usr/local/bin/exiftool` (homebrew path) to get it working.

Do you not lookup the executable in `$PATH`. Regarding the current value `/usr/bin/exiftool` - wasn't it that some security feature does us not even allow us device owners anymore to install programs there?

**Comment by flingo64** [comment]
It's not a hardcoded path, it's a hardcoded _default path_, that of course can be adjusted in the Export or Publish dialog. 

I'm using the Lr API, I have no acccess to $PATH. Also, I'm  not an Mac user, so I'm not aware of these constraints.

If you can suggest a suitable default path, this may go to the next release.

**Comment by StephenKing** [comment]
Ah, indeed :-) Found the setting. Not sure, what a better path is - for MacOS it really might be `/usr/local/bin/exiftool`. A small hint where to change the setting would be sufficient, I guess. Thanks!
