### ISSUE TITLE
Interner Fehler PSPhotosAPU.ua 1024

### ISSUE THREAD

**Issue by Feilner** [flingo64/PhotoStation-Upload-Lr-Plugin#71]
Ideen?
![image](https://user-images.githubusercontent.com/6040107/221403439-f5f57f21-0fc0-487c-aab1-5253e62848b0.png)

**Comment by flingo64** [comment]
It seems you are using v7.2.2. Please, update to 7.3.0, the bug was fixed recently.

**Comment by Feilner** [comment]
Thanks! I updated it and the error is gone! 
But I got a new one in context of exporting videos:
![image](https://user-images.githubusercontent.com/6040107/222132763-f5a611af-78fc-4470-a935-5e09f7cc4e17.png)

**Comment by flingo64** [comment]
There seem to be two issues:
1. there is an issue with the blank in the filename '1992.06.27 Heubühl.mp4': Lr derives only  '1992.06' from it for the local rendered upload filename. so the plugin assumes the rendered extension to be '06' and applies this as extension to the target filename. This does not happen with Lr 6.14. 
2. ````pathIdCacheGetEntry(user='0', path='/', 'folder') returns 'notCached'````: this is a 'should-not-happen' case:  the path cache is pre-filled with the root folder and ther should be no way to remove it. No idea how this can happen
Can you retest with a video w/o blanks in the filename? If the second issue still exists, I would need the whole logfile including the exportParams listing.

**Comment by flingo64** [comment]
Should be fixed in 7.3.x.
Please re-open if the issue still exists
