### ISSUE TITLE
Synology Photos 1.6 - ErrorCode 12045

### ISSUE THREAD

**Issue by greddin** [flingo64/PhotoStation-Upload-Lr-Plugin#75]
Hi, I've done the initial configuration of Photo StatLR but when I click Publish in LR I'm getting this error message.

Booo!!
Initialization of Global Photos 1.3 () at https://192.168.1.2:5001 failed!
Reason Unknown ErrorCode: 12045

Here's the log file:

8:00:03 PM, INFO : Environment: plugin: 7.3.2.20230519 Lr: 13.0.1 OS: Windows 11 - Business Edition Lang: en
8:00:03 PM, INFO : processRenderedPhotos starting
8:00:03 PM, ERROR: Initialization of Global  Photos 1.3 () at
https://192.168.1.2:5001
failed!
Reason: Unknown ErrorCode: 12045
8:00:03 PM, INFO : Photo StatLr: Publish failed!: Initialization of Global  Photos 1.3 () at
https://192.168.1.2:5001
failed!
Reason: Unknown ErrorCode: 12045

8:00:06 PM, INFO : Get comments: nothing to do.
8:00:06 PM, INFO : Get ratings/metadata: nothing to do.

===============

Is there anything here that could indicate what my issue is?

Thank you,
-Greg

**Comment by flingo64** [comment]
ErrorCodes 120xx are generated by the LrHttp API. Raise the loglevel to DEBUG to get more detailed error info in the logfile.
Most likely, the error is related to the server cert. Try with http and port 5000 to verify this.

**Comment by greddin** [comment]
Thank you, this was the issue.
