### ISSUE TITLE
Metadata Download Tags/Keywords not updating

### ISSUE THREAD

**Issue by greddin** [flingo64/PhotoStation-Upload-Lr-Plugin#76]
As I understand it, any new tags/keywords that get added from Synology Photos can be synced back into LR?  

I've published a small collection and configured it to download the Tags/Keywords as well.  After the publish I went into Synology Photos and added a couple of new tags on a photo.  Marked it for publishing again and ran the publish.  Afterwards, I don't see the new tags on the photo in LR.  

I'm using Synology Photos 1.6. 

Am I doing the workflow correctly?

Thanks,
-Greg

**Comment by flingo64** [comment]
That not the way it works. Downloading of metadata is done via the Lr method for fetching comments on published photos.
Check out the documentation on [Two-way sync of metadata](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/Documentation/07-Publish-Some%20words%20on%20the%20two%20way%20sync%20of%20metadata.md).

**Comment by flingo64** [comment]
No feedback, closing the issue
