### ISSUE TITLE
One photo will never get published

### ISSUE THREAD

**Issue by bernic** [flingo64/PhotoStation-Upload-Lr-Plugin#77]
Hello,
I just installed your plugin (Great plugin!! thank you by the way).
I run Lightroom classic 13 on windows 11 with a DS 216II+ on DSM 7.2 and photo station 1.5

after a few issue to got it working (it seemed that without signed certificat it wasn't working even over http for some reasons)
I also kept getting some minor errors (and got one crash) but I just need to relaunch the publication to carry on so it was ok for me. so far 

However there is one error I keep getting all the time, usually just after hitting the publish button : 

> RecordPublishedPhotoUrl:  must be called after RecordPublishedPhotoId

After this error it carries on, except for the last photo it will just throw the error and never publish it.

Let me know if you need more information  
Regards

**Comment by flingo64** [comment]
The issue and some ideas how to fix it is described [here](https://github.com/flingo64/PhotoStation-Upload-Lr-Plugin/blob/master/Documentation/22-Error-Publish-recordPublishedPhotoUrl%20-%20must%20be%20called%20after%20recordPublishedPhotoId.md).

**Comment by bernic** [comment]
Great thank you for the explaination.

________________________________
