### ISSUE TITLE
Getting Unknown ErrorCode: -1202

### ISSUE THREAD

**Issue by drissslim** [flingo64/PhotoStation-Upload-Lr-Plugin#78]
Hello,
I've encoutred today this issue when tried to publish photos : Reason: Unknown ErrorCode: -1202

Thank you for your help.

Below the error that I'm getting is here : 

``
17:31:42, INFO : didUpdatePublishService: adding Shared Album Keyword Hierarchy 'Photo StatLr|Shared Albums|Phtos & Videos on driss.info'
17:31:42, DEBUG: getKeywordByPath('Photo StatLr|Shared Albums|Phtos & Videos', create: true, include: false) returns keyword id 15388500
17:31:49, INFO : PSInitPlugin:
		convert: '/usr/local/bin/convert'
		dcraw: '/usr/local/bin/dcraw'
		exiftool:   '/usr/local/bin/exiftool'
		ffmpeg:     '/usr/local/bin/ffmpeg'
17:31:49, INFO : PSInitPlugin: Successfully added 2 custom video export presets.
17:31:49, TRACE: updateExportSettings: done.
17:31:49, INFO : Environment: plugin: 7.3.2.20230519 Lr: 12.5.1 OS: 11.7.10.20G1427 Lang: en
17:31:58, INFO : processRenderedPhotos starting
17:31:58, TRACE: openSession(operation = ProcessRenderedPhotos, publishMode = Publish) starting ...
17:31:58, DEBUG: Photos.new(url=https://192.168.1.253:5443, personal=false, persUser=, timeout=10, version=73, username=slim, password=*************)
17:31:58, TRACE: pathIdCacheInitialize(user='0')
17:31:58, DEBUG: Photos_API: LrHttp.post(url='https://192.168.1.253:5443/webapi/query.cgi', API=SYNO.API.Info params='version=1&api=SYNO.API.Info&method=query&query=SYNO.API.,SYNO.Foto.,SYNO.FotoTeam.')
17:31:58, TRACE: "respHeaders":{
17:31:58, TRACE: 	"error":{
17:31:58, TRACE: 		"errorCode":"securityError"
17:31:58, TRACE: 		"name":"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.253” which could put your confidential information at risk."
17:31:58, TRACE: 		"nativeCode":"-1202"
17:31:58, TRACE: 	}
17:31:58, TRACE: }
17:31:58, TRACE: Error securityError on http request: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.253” which could put your confidential information at risk.
17:31:58, ERROR: Initialization of Global  Photos 1.3 () at
https://192.168.1.253:5443
failed!
Reason: Unknown ErrorCode: -1202
17:31:58, INFO : Photo StatLr: Publish failed!: Initialization of Global  Photos 1.3 () at
https://192.168.1.253:5443
failed!
Reason: Unknown ErrorCode: -1202

17:32:04, TRACE: openSession(operation = DeletePhotosFromPublishedCollection, publishMode = Delete) starting ...
17:32:04, DEBUG: Photos.new(url=https://192.168.1.253:5443, personal=false, persUser=, timeout=10, version=73, username=slim, password=**********)
17:32:04, TRACE: pathIdCacheInitialize(user='0')
17:32:04, DEBUG: Photos_API: LrHttp.post(url='https://192.168.1.253:5443/webapi/query.cgi', API=SYNO.API.Info params='version=1&api=SYNO.API.Info&method=query&query=SYNO.API.,SYNO.Foto.,SYNO.FotoTeam.')
17:32:04, TRACE: "respHeaders":{
17:32:04, TRACE: 	"error":{
17:32:04, TRACE: 		"errorCode":"securityError"
17:32:04, TRACE: 		"name":"The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.253” which could put your confidential information at risk."
17:32:04, TRACE: 		"nativeCode":"-1202"
17:32:04, TRACE: 	}
17:32:04, TRACE: }
17:32:04, TRACE: Error securityError on http request: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “192.168.1.253” which could put your confidential information at risk.
17:32:04, ERROR: Initialization of Global  Photos 1.3 () at
https://192.168.1.253:5443
failed!
Reason: Unknown ErrorCode: -1202
17:32:04, INFO : Photo StatLr: Delete photos failed!: Initialization of Global  Photos 1.3 () at
https://192.168.1.253:5443
failed!
Reason: Unknown ErrorCode: -1202

``

**Comment by flingo64** [comment]
As stated in the logfile ` The certificate for this server is invalid.`
Either use http or install a server certificate with '192.168.1.253' as hostname.

**Comment by flingo64** [comment]
No response - closing issue.
